blog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired

class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

blog/main/routes.py
from flask import Blueprint, request, render_template
from blog.models import Post
main = Blueprint('main', __name__)


@main.route("/")
def home_page():
    page_number = request.args.get('page',1,type=int) # 1 is the default value
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(per_page=5, page=page_number)
    return render_template('home.html', posts=posts)

@main.route("/about")
def about_page():
    return render_template('about.html', title='About')

blog/posts/routes.py
from flask import Blueprint, request, render_template, redirect, url_for, flash, abort
from flask_login import current_user, login_required
from blog.models import Post
from blog.posts.forms import PostForm
from blog import db

posts = Blueprint('posts', __name__)


@posts.route('/post/new', methods=['Get', 'Post'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash(f'Post created successfully', category='success')
        return redirect(url_for('main.home_page'))
    return render_template('create_post.html', title='New Post', form=form, lengend='New Post')

@posts.route("/post/<int:post_id>")
@login_required
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)

@posts.route('/post/<int:post_id>/update', methods=['Get', 'Post'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash(f'Your post has been updated!', category='success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post', form=form, legend='Update Post')

@posts.route('/post/<int:post_id>/delete', methods=['Post'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash(f'Your post has been deleted.', category='success')
    return redirect(url_for('main.home_page'))

blog/users/routes.py
from flask import Blueprint, redirect, render_template, flash, url_for, request
from flask_login import current_user, login_user, logout_user, login_required
from blog import bcrypt, db
from blog.models import User, Post
from blog.users.utils import save_picture, send_reset_email
from blog.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm

users = Blueprint('users', __name__)

@users.route("/register", methods=['Get', 'Post'])
def register_page():
    if current_user.is_authenticated:
        return redirect(url_for('main.home_page'))
    form = RegistrationForm()
    if form.validate_on_submit():
        password_hash = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        new_user = User(username=form.username.data, email=form.email.data, password=password_hash)
        db.session.add(new_user)
        db.session.commit()

        flash(f'Account created for {form.username.data}! Please log in', category='success')
        return redirect(url_for('users.login_page'))
    return render_template('register.html', title='Register', form=form)

@users.route("/login", methods=['Get', 'Post'])
def login_page():
    if current_user.is_authenticated:
        return redirect(url_for('main.home_page'))
    form = LoginForm()
    if form.validate_on_submit():
        exist_user = User.query.filter_by(email=form.email.data).first()
        if exist_user and bcrypt.check_password_hash(exist_user.password, form.password.data):
            login_user(exist_user, remember=form.remember.data)
            next_page = request.args.get('next') # args is dict. we can args['next'], but this will throw an error whenever they cannot find next. So get will throw None, which is better.
            if next_page:
                next_page = next_page.split('/')
            flash(f'Logged in as {form.email.data}!', category='success')
            return redirect(f'{next_page[-1]}_page') if next_page else redirect(url_for('main.home_page'))
        else:
            flash('Login Unsuccessful! Please check email and password', category='danger')
    return render_template('login.html', title='Login', form=form)

@users.route('/logout')
def logout_page():
    logout_user()
    return redirect(url_for('main.home_page'))


@users.route("/account", methods=['Get', 'Post'])
@login_required
def account_page():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            current_user.image_file = save_picture(form.picture.data)
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.add(current_user)
        db.session.commit()
        flash('Account information updated!', category='success')
        return redirect(url_for('users.account_page'))
    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/'+str(current_user.image_file))
    return render_template('account.html', title='Account', image_file=image_file,form=form)

@users.route("/user/<string:username>")
def user_posts(username):
    page_number = request.args.get('page',1,type=int) # 1 is the default value
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post\
        .query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(per_page=5, page=page_number)
    return render_template('user_posts.html', posts=posts, user=user)

@users.route('/reset_password', methods=['Get', 'Post'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home_page'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash(f'An email has been sent with instructions to reset your password', category='info')
        return redirect(url_for('users.login_page'))
    return render_template('reset_request.html', title='Reset Password', form=form)

@users.route('/reset_password/<token>', methods=['Get', 'Post'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home_page'))
    user = User.verify_reset_token(token)
    if user is None:
        flash(f'That is an invalid or expired token.', category='warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        password_hash = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = password_hash
        db.session.commit()
        flash(f'Your password has been updated! Please log in', category='success')
        return redirect(url_for('users.login_page'))
    return render_template('reset_token.html', title="Reset Password", form=form)

blog/templates/about.html
{% extends "base.html" %}

{% block body %}
    <h1>About Page</h1>
    
{% endblock %}

blog/templates/account.html
{% extends "base.html" %} {% block body %}
<div class="content-section">
    <div class="d-flex">
        <div class="flex-grow-0">
            <img class="rounded-circle account-img" src="{{ image_file }}" />
        </div>
        <div class="flex-grow-1 ms-3">
            <h2 class="account-heading">{{ current_user.username }}</h2>
            <p class="text-secondary">{{ current_user.email }}</p>
        </div>
    </div>
    <!-- FORM HERE -->
    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset>
            <legend class="border-bottom mb-4">Account Info</legend>
            {{ form.username.label(class="form-control-label") }} 
            <div class="input-group  mb-3">
                {% if form.username.errors %} 
                {{ form.username(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %} 
                {{ form.username(class="form-control form-control-lg") }} 
                {% endif %}
            </div>
            {{ form.email.label(class="form-control-label") }} 
            <div class="input-group  mb-3">
                {% if form.email.errors %} 
                {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %} {{ form.email(class="form-control form-control-lg")
                }} {% endif %}
            </div>
            {{ form.picture.label() }}
            <div class="input-group  mb-3">
                {{ form.picture(class="form-control form-control-sm") }}
                {% if form.picture.errors %}
                    {% for error in form.picture.errors %}
                        <span class="text-danger">{{ error }}</span><br>
                    {% endfor %}
                {% endif %}
        </fieldset>
        <div class="input-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock %}

blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='main.css')}}">
    {% if title %}
        <title>Flask Blog - {{ title }}</title>
    {% else %}
        <title>Flask Blog</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
          <div class="container">
            <a class="navbar-brand mr-4" href="/">Flask Blog</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <div class="navbar-nav me-auto">
                <a class="nav-item nav-link" href=" {{ url_for('main.home_page') }} ">Home</a>
                <a class="nav-item nav-link" href="{{ url_for('main.about_page')}}">About</a>
              </div>
              <!-- Navbar Right Side -->
              <div class="navbar-nav">
                {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                <a class="nav-item nav-link" href="{{ url_for('users.account_page') }}">Account</a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout_page') }}">Logout</a>
                {% else %}
                  <a class="nav-item nav-link" href="{{ url_for('users.login_page') }}">Login</a>
                  <a class="nav-item nav-link" href="{{ url_for('users.register_page') }}">Register</a>
                {% endif%}
              </div>
            </div>
          </div>
        </nav>
    </header>
    <main role="main" class="container">
        <div class="row">
          <div class="col-md-8">
            {% with messages = get_flashed_messages(with_categories=true) %}
              {% if messages %}
                  {% for category, message in messages %}
                      <div class="alert alert-{{category}} alert-dismissible fade show" role="alert">
                          {{ message }}
                          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
                          </button>              
                      </div>
                  {% endfor %}
              {% endif %}
            {% endwith %}
            {% block body %}{% endblock %}
          </div>
          <div class="col-md-4">
            <div class="content-section">
              <h3>Our Sidebar</h3>
              <p class='text-muted'>You can put any information here you'd like.
                <ul class="list-group">
                  <li class="list-group-item list-group-item-light">Latest Posts</li>
                  <li class="list-group-item list-group-item-light">Announcements</li>
                  <li class="list-group-item list-group-item-light">Calendars</li>
                  <li class="list-group-item list-group-item-light">etc</li>
                </ul>
              </p>
            </div>
          </div>
        </div>
      </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/create_post.html
{% extends 'base.html' %} {% block body %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset>
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            {{ form.title.label(class="form-label") }}
            <div class="input-group mb-3">
                {% if form.title.errors %} {{ form.title(class="form-control
                form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.title.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %} {{ form.title(class="form-control form-control-lg")
                }} {% endif %}
            </div>
            {{ form.content.label(class="form-control-label") }}
            <div class="input-group mb-3">
                {% if form.content.errors %} {{ form.content(class="form-control
                form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.content.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %} {{ form.content(class="form-control form-control-lg")
                }} {% endif %}
            </div>
        </fieldset>
        <div class="input-group mb-3">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock %}

blog/templates/home.html
{% extends "base.html" %} 
{% block body %} 
{% for post in posts.items %}
<article class="d-flex content-section">
    <img
        class="rounded-circle article-img flex-shrink-0"
        src="{{ url_for('static', filename='profile_pics/' + post.author.image_file)}}"
        alt=""
    />
    <div class="flex-grow-1 ms-3">
        <div class="article-metadata">
            <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        </div>
        <h2>
            <a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a>
        </h2>
        <p class="article-content">{{ post.content }}</p>
    </div>
</article>
{% endfor %} 
{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
        {% if posts.page == page_num %}
            <a class="btn btn-info mb-4" href="{{ url_for('main.home_page', page=page_num) }}">{{ page_num }}</a>
        {% else %}
            <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home_page', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
    {% else %}
            ...
    {% endif %}

{% endfor %}

{% endblock %}

blog/templates/login.html
{% extends "base.html" %} {% block body %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="mb-3">
            <legend class="border-bottom mb-4">Log In</legend>
            <div class="mb-3">
                {{ form.email.label(class="form-control-label") }} {% if
                form.email.errors %} {{ form.email(class="form-control
                form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %} {{ form.email(class="form-control form-control-lg")
                }} {% endif %}
            </div>
            <div class="mb-3">
                {{ form.password.label(class="form-control-label") }} {% if
                form.password.errors %} {{ form.password(class="form-control
                form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %} {{ form.password(class="form-control
                form-control-lg") }} {% endif %}
            </div>
            <div class="form-check">
                {{ form.remember(class="form-check-input")}} {{
                form.remember.label(class="form-check-label")}}
            </div>
        </fieldset>
        <div class="mb-3">
            {{ form.submit(class="btn btn-outline-info") }}
            <small class="text-muted ml-2">
                <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
            </small>
        </div>
    </form>
</div>
<div class="border-top pt-3">
    <small class="text-muted">
        Need An Account?
        <a class="ml-2" href="{{ url_for('users.register_page') }}">Sign Up Now</a>
    </small>
</div>

{% endblock %}

blog/templates/post.html
{% extends "base.html" %} {% block body %}
<article class="d-flex content-section">
    <img
        class="rounded-circle article-img flex-shrink-0"
        src="{{ url_for('static', filename='profile_pics/' + post.author.image_file)}}"
        alt=""
    />
    <div class="flex-grow-1 ms-3">
        <div class="article-metadata">
            <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
            <small class="text-muted"> {{ post.date_posted.strftime('%Y-%m-%d') }} </small>
            {% if post.author == current_user %}
            <div>
                <a class="btn btn-secondary btn-sm ms-0 m-1" href="{{ url_for('posts.update_post', post_id=post.id) }}"
                    >Update</a
                >
                <button
                    data-bs-toggle="modal"
                    data-bs-target="#deleteModal"
                    type="button"
                    class="btn btn-danger btn-sm m-1"
                >
                    Delete
                </button>
            </div>
            {% endif %}
        </div>
        <h2 class="article-title">{{ post.title }}</h2>
        <p class="article-content">{{ post.content }}</p>
    </div>
</article>
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Delete Post?</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <form action="{{url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Delete" />
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/register.html
{% extends "base.html" %}

{% block body %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset>
            <legend class="border-bottom mb-4">Join Today</legend>
            <div class="mb-3">
                {{ form.username.label(class="form-control-label") }}

                {% if form.username.errors %}
                    {{ form.username(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.username(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="mb-3">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="mb-3">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="mb-3">
                {{ form.confirm_password.label(class="form-control-label") }}
                {% if form.confirm_password.errors %}
                    {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.confirm_password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.confirm_password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="mb-3">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
<div class="border-top pt-3">
    <small class="text-muted">
        Already Have An Account? <a class="ml-2" href="{{ url_for('users.login_page') }}">Sign In</a>
    </small>
</div>
    
{% endblock %}

blog/templates/reset_request.html
{% extends "base.html" %} {% block body %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Reset Password</legend>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }} {% if
                form.email.errors %} {{ form.email(class="form-control
                form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %} {{ form.email(class="form-control form-control-lg")
                }} {% endif %}
            </div>       
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>

{% endblock %}

blog/templates/reset_token.html
{% extends "base.html" %} {% block body %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Reset Password</legend>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }} {% if
                form.password.errors %} {{ form.password(class="form-control
                form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %} {{ form.password(class="form-control form-control-lg")
                }} {% endif %}
            </div>       
            <div class="form-group">
                {{ form.confirm_password.label(class="form-control-label") }} {% if
                form.confirm_password.errors %} {{ form.confirm_password(class="form-control
                form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.confirm_password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %} {{ form.confirm_password(class="form-control form-control-lg")
                }} {% endif %}
            </div> 
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock %}

blog/templates/user_posts.html
{% extends "base.html" %} 
{% block body %} 
<h1 class="mb-3"> Posts by {{ user.username }} ( {{ posts.total }} )</h1>
{% for post in posts.items %}
<article class="media content-section">
    <img
        class="rounded-circle article-img"
        src="{{ url_for('static', filename='profile_pics/' + post.author.image_file)}}"
        alt=""
    />
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        </div>
        <h2>
            <a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a>
        </h2>
        <p class="article-content">{{ post.content }}</p>
    </div>
</article>
{% endfor %} 
{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
        {% if posts.page == page_num %}
            <a class="btn btn-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% else %}
            <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
        {% endif %}
    {% else %}
            ...
    {% endif %}

{% endfor %}

{% endblock %}